package org.example;

public enum RequestServer {
    REQUESR_GET_RECORDS_FOR_DAY("REQUESR_GET_RECORDS_FOR_DAY"),
    REQUESR_GET_RECORDS_FOR_DAY_MASTER("REQUESR_GET_RECORDS_FOR_DAY_MASTER"),
    REQUESR_GET_RECORDS_FOR_DATE_MASTER_RANGE("REQUESR_GET_RECORDS_FOR_DATE_MASTER_RANGE"),
    REQUESR_GET_ALL_MASTERS("REQUESR_GET_ALL_MASTERS"),
    REQUESR_GET_MASTERS_FOR_DAY_RANGE("REQUESR_GET_MASTERS_FOR_DAY_RANGE"),
    REQUESR_GET_WORKING_MASTERS_FOR_DAY("REQUESR_GET_WORKING_MASTERS_FOR_DAY"),
    REQUESR_GET_TIME_FOR_DAY("REQUESR_GET_TIME_FOR_DAY"),
    REQUESR_GET_ALL_TIME("REQUESR_GET_ALL_TIME"),
    REQUESR_CHECK_USER("REQUESR_CHECK_USER"),
    REQUESR_CHECK_MASTER("REQUESR_CHECK_MASTER"),
    REQUESR_ADD_MASTER("REQUESR_ADD_MASTER"),
    REQUESR_UPDATE_MASTER("REQUESR_UPDATE_MASTER"),
    REQUESR_DELETE_MASTER("REQUESR_DELETE_MASTER"),
    REQUESR_ADD_RECORD("REQUESR_ADD_RECORD"),
    REQUESR_EDIT_RECORD("REQUESR_EDIT_RECORD"),
    REQUESR_DELETE_RECORD("REQUESR_DELETE_RECORD"),
    REQUESR_GET_ALL_PROCEDURE("REQUESR_GET_ALL_PROCEDURE"),
    REQUESR_GET_REPORT("REQUESR_GET_REPORT"),
    REQUESR_GET_HISTORY("REQUESR_GET_HISTORY"),
    REQUESR_MOVE_RECORD("REQUESR_MOVE_RECORD");

    private String nameRequest;

    RequestServer(String nameRequest){
        this.nameRequest = nameRequest;
    }

    public String getNameRequest() {
        return nameRequest;
}
}
